getsentry/taskbroker

- python/integration_tests/test_consumer_rebalancing.py
Small fix for improving logging in the integration test. Instead of dumping all consumer logs (GHA refuses to print all logs), when an error log is seen, capture 10 lines before and after the error and print to stdout.
> fix(tests): Fix logging integration test

- devservices/config.yml
With the revamped devservices, the configurations for how to run taskbroker should live in this repo and not sentry. 
See snuba: https://github.com/getsentry/sentry/blob/ec05e95588181966ded878090b1241e3b3fb2775/devservices/config.yml#L6
This allows configurations to be defined in the appropriate repo and be used anywhere else.
> feat(devservices): Add containerized taskbroker to devservices config

- src/config.rs
- src/logging.rs
We need a traces_sample_rate in order to collect tracing data. With this change made I was able to validate that tracing data is being collected and sent to sentry.
> fix(config) Add traces_sample_rate config

- devservices/config.yml
Adding the orchestrator label to the devservices config
> fix(devservices): Adding orchestrator label

- src/consumer/kafka.rs
Removes incremental rebalancing logic from the kafka consumer state machine.
We currently have a working implementation [here](https://github.com/getsentry/taskbroker/pull/99). However, taking advantage of incremental rebalancing requires a little further work:
- The rdkafka library currently has a bug with committing consumer offset manually during incremental rebalance, causing the consumer to lose its assignment when encountering an illegal generation error. We generally don't use manual offset commit and utilize the auto commit from rdkafka, but we still manually commit offset on shutdown signals. The way the PR above works around this issue is to shutdown the actors, poll the consumer for a predetermined amount of time before actually shutting down. But to use this in production we …
> ref(kafka): Remove incremental rebalancing

- k8s/README.md
- k8s/k8s_stateful_set.yaml
- k8s/k8s_storage_class.yaml
This adds two k8s config files: one to create the storage class used for sqlite, and another to run the taskbroker service itself.
The service currently uses a specific cloud image. This should be fixed in the future to be locked to the latest build of the image, instead of a specific commit.
There are some rough instructions in the README on how to apply this k8s config to a sandbox for testing.
> feat(k8s): Add basic k8s config files

- config/config-dev.yaml
- config/config-sentry-dev.yaml
- src/config.rs
- src/consumer/admin.rs
- src/consumer/kafka.rs
- src/consumer/mod.rs
- src/main.rs
In dev situations, it is possible for the taskbroker to be started without the necessary topics existing locally. Add a function that will create the topics if they don't exist. This function can be skipped with a config setting.
This is necessary for a couple reasons: The taskbroker runs independently of sentry itself, in the same way snuba/relay run independently. That means it should be possible to start taskbroker without needing to start the sentry monolith. These types of applications are managed using the `devservices` commands (vs. `devserver`, which starts the monolith).
However, `devservices` has no mechanism to run commands on the dependent services, which is necessary in the `taskbroker` case to initialize the kafka topics.
In order to have `taskbroker` be independent of the …
> feat(kafka): Create the topics if they don't exist

- src/inflight_activation_store.rs
Sqlite doesn't have a storage class specific for datetime type. Instead, it stores datetimes as TEXT, REAL or INTEGER values. The way we store it is `TEXT as an ISO8601 string ("YYYY-MM-DDTHH:MM:SS.SSS")`. In both `handle_processing_deadline()` and `handle_deadletter_at()`, we inject a `now()` timestamp string into the SQL query. As a result, this produced incorrect results when trying compare a datetime with string or string with string.
See the following two examples. Both time stamps only contain differences in the seconds. The first resolves `true` as we expect, the second example also resolves `true` unexpectedly. 
```
sqlite> SELECT datetime('2024-12-20T20:20:20.10001Z') < '2024-12-20T20:20:21.10001Z';
1
sqlite> SELECT datetime('2024-12-20T20:20:20.10001Z') < …
```
> fix(activation-store): Fix datetime comparison

- .github/workflows/ci.yml
- Makefile
- python/integration_tests/helpers.py
- python/integration_tests/test_consumer_rebalancing.py
1. Separate the unit tests and integration test into separate CI checks
2. Unify make file and CI so that the CI uses the makefile as much as possible. This way, it's much easier to reproduce CI failure locally.
3. Destroys the kafka container and volume before starting an integration test, so all integration tests can start with a clean kafka container.
4. Update the integration test output directory structure from:
```
.
└── integration_tests/
└── .test_output/
└── # Files all go in here
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to:
```
.
└── integration_tests/
└── .test_output/
├── rebalance/
│   └── # rebalance output goes here
└── some_other_test/
└── # output for the other test goes here
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; so that finding integration tests would be easier as we …
> test(kafka): Refactor integration tests

- k8s/README.md
- k8s/k8s_stateful_set.yaml
- k8s/k8s_taskworker.yaml
- python/integration_tests/runner.py
- python/integration_tests/test_task_worker_processing.py
- python/integration_tests/worker.py
This adds a k8s file for deploying the taskworker image. It also makes a few QoL improvements:
- Replace SimpleTaskWorker with ConfigurableTaskWorker
- Add more logging to the worker
- Add a backoff to the worker, so that if there are no messages it doesn't spam logs
- Update the taskbroker image
- Fix a bug in the worker where it wouldn't process tasks fetched in the update
> ref(k8s): Add a k8s for the taskworker deployment

- .github/workflows/.vscode/settings.json
- .github/workflows/ci.yml
- Makefile
- python/integration_tests/helpers.py
- python/integration_tests/test_consumer_rebalancing.py
- python/integration_tests/test_task_worker_processing.py
- python/integration_tests/test_upkeep_retry.py
- python/integration_tests/worker.py
This tests is responsible for checking the integrity of the retry mechanism implemented in the upkeep thread of taskbroker. An initial amount of messages is produced to kafka with a set number of retries in its retry policy. Then, the taskworkers fetch and update the task's status to retry. During an interval, the upkeep thread will collect these tasks and re-produce the task to kafka. This process continues until all tasks have been retried the specified number of times.
The test starts N number of taskworker(s) and a consumer in separate
threads. Synchronization events are use to instruct the taskworker(s) when start processing and shutdown. A shared data structured access by a mutex called TaskRetriedCounter is used to globally keep track of every task retried. Finally, this total …
> feat(tests): End-to-end integration for upkeep retry

- migrations/0001_create_inflight_taskactivations.sql
- src/config.rs
- src/consumer/deserialize_activation.rs
- src/inflight_activation_store.rs
- src/test_utils.rs
- src/upkeep.rs
The name deadletter_at was a bit misleading as activations past this
deadline were not always deadlettered. Based on an activation's retry
policy they could be discarded as well.
Refs https://github.com/getsentry/taskbroker/issues/117
> Rename deadletter_at -> remove_at

- migrations/0001_create_inflight_taskactivations.sql
- src/consumer/deserialize_activation.rs
- src/inflight_activation_store.rs
- src/test_utils.rs
- src/upkeep.rs
SQlite doesn't have a specific storage type for datetime values and uses TEXT instead. This requires careful use of `datetime()` functions on value. By switching to INTEGER columns we won't get burned by future changes to datetime logic if we forget a function. It should also result in smaller database sizes. sqlx includes trait implementations to convert `DateTime<Utc>` into a timestamp already and from a timestamp into `DateTime<Utc>`.
I've also made `remove_at` required as we should not store an activation that cannot be purged in the future.
Fixes #111
> Replace DATETIME columns with INTEGER

- src/inflight_activation_store.rs
- src/upkeep.rs
There are two unit tests in `src/upkeep.rs` which are passing as false positives: 
* `test_retry_is_discarded_when_exhausted_with_retry`
* `test_retry_is_discarded_with_no_retry_state`
Both these tests assert that the inflight activation store only contains one pending task and assumes that the other retry task was discarded. However, this is not the case. Rather than being discarded, the task is being reproduced to the topic. In the [task activation state machine ](https://www.notion.so/sentry/Taskbroker-Taskworkers-74a84c8b1992480190c380e282f87778?pvs=4#90fe2c8a1abf4a2eaf98b4a97c055f22), there is no path for a retry task to be discarded or dlq'ed. Instead, it is follows the following flow:
1. Retry task is reproduced as pending and attempts is incremented
2. Worker picks up the pending …
> ref(upkeep): Make do_upkeep return context and update tests

- Makefile
- python/requirements-dev.txt
Add make targets for checking and applying formatting with black. I'm planning to integrate these into CI and local development tooling.
> feat(tooling) Add black and makefile target for formatting

- .github/workflows/ci.yml
- Makefile
- python/integration_tests/helpers.py
- python/integration_tests/test_consumer_rebalancing.py
- python/integration_tests/test_task_worker_processing.py
- python/integration_tests/test_upkeep_dlq.py
- python/integration_tests/test_upkeep_retry.py
- python/integration_tests/worker.py
This tests is responsible for checking the integrity of the discard and deadletter mechanism implemented in the upkeep thread of taskbroker. An initial amount of messages is produced to kafka where half of the messages' on_attempts_exceeded is set to discard and the other half to deadletter. These messages have an `expires` value of 1 second. An extra message is produced to the topic which is to be completed by a taskworker first. This allows all the previous messages to be discarded/deadlettered by upkeep. During an interval, the upkeep thread collect all tasks that have expired, sets them all to a failed status, then appropriately discards or deadletters these messages. This process continues until all tasks have have a completed status (this means all tasks have either been discarded …
> feat(tests): End-to-end integration for upkeep DLQ 

- Cargo.lock
- Cargo.toml
- src/grpc_server.rs
Instead of sending the raw internal error to the client, log the error in the broker and send a more generic message to the client. This will also indicate that there is an error on the broker. Otherwise the error would only appear in the worker.
> fix(grpc): Send more appropriate error message

- src/inflight_activation_store.rs
Instead of using `max(offset)` to determine which tasks to expire and complete, use `max(added_at)` instead. This ensures that we don't have inconsistency as tasks of multiple partitions can live on the same sqlite.
Fixes: https://github.com/getsentry/taskbroker/issues/137
> feat(taskbroker): Use earliest task instead of oldest for handling removals

- src/upkeep.rs
For some reason gauges does not work with the metrics library we're using. What we can do is to emit counters and set those values to gauges on datadog.
I think for now this is an acceptable solution because I don't think we should waste too much time debugging the datadog agent in the sandbox, as the metrics configuration would be quite different between the sandbox and production anyway.
> ref(tele): Use counters for now

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/lib.rs
- src/logging.rs
I was trying to figure out how to get rid of the annoying h2 logs
```
2025-01-30T07:17:43.333156Z DEBUG Connection: h2::codec::framed_read: received frame=Headers { stream_id: StreamId(7), flags: (0x4: END_HEADERS) } peer=Server
2025-01-30T07:17:43.333259Z DEBUG Connection: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(7), size_increment: 5 } peer=Server
2025-01-30T07:17:43.333311Z DEBUG Connection: h2::codec::framed_read: received frame=Data { stream_id: StreamId(7), flags: (0x1: END_STREAM) } peer=Server
2025-01-30T07:17:43.334691Z DEBUG Connection: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(7), flags: (0x5: END_HEADERS | END_STREAM) } peer=Server
```
After figuring it out I realize I'll need to create yet another thing in the config …
> feat(telemetry): A single place to configure log filtering

- python/requirements-dev.txt
This bumps devservices to version 1.0.14 since the version here seems to be pretty outdated.
> chore(devservices): Bump devservices to 1.0.14

- src/grpc_server.rs
- tests/grpc_server_test.rs
I was debugging the `set_task_status` grpc code and I found it a little bit difficult to follow with the mutation and high level of nesting.
Let me know if this is actually easier to read, I am obviously biased
> ref(grpc): Refactor set_task_status

- migrations/0001_create_inflight_taskactivations.sql
The UUID type is a generic type in SQLite, which automatically tries to convert values into numbers where possible. Since some UUIDs are also valid numbers, SQLite was converting those values to numbers. This was generally fine except for UUIDs that had just numbers, with a lower case 'e', and then more numbers, e.g. 97033619637148748591279e7866347. SQlite would interpret the `e` as an exponent character, and end up storing +Inf.
This is all avoided by storing the key as a TEXT string, which prevents this type of interpolation.
> fix(sqlite): Change id column from UUID to TEXT

- python/integration_tests/test_upkeep_dlq.py
Two minutes for the consumer to completely DLQ/discarding 10,000 tasks might have been over ambitious. Let's bump it to 10 minutes and see if it fixes flaky test.
> fix(dlq-test): bump consumer timeout to 10 min

- src/config.rs
- src/consumer/inflight_activation_batcher.rs
- src/consumer/inflight_activation_writer.rs
- src/consumer/mod.rs
- src/main.rs
Adds a batching step in front of the db write step.
The current Sqlite write step works like so:
1. When a message come in from the previou step, it queries to see if size(db) + size(buffer) is smaller than max pending tasks, if it is, add the message to the buffer.
2. When size(db) + size(buffer) is equal to the max pending tasks, or every 4 seconds, flush the buffer to the db
This worked reasonably well but it requires us to make a query each time we see a message. By separating the batching step before the writer, we only need to query the DB every `max_pending_buffer_count` messages.
> feat(consumer): Improve consumer write throughput

- python/integration_tests/test_consumer_rebalancing.py
There're certain runs of the rebalance integration test where the number of messages are distributed unevenly amongst the partitions and thus distributed unevenly amongst the consumers
For example [this run](https://github.com/getsentry/taskbroker/actions/runs/13152142746/job/36702863955?pr=166)
```
======== Number of rows in each taskbroker ========
Consumer 0: 3539, 23% of capacity
Consumer 1: 14994, 99% of capacity
Consumer 2: 14976, 99% of capacity
Consumer 3: 14975, 99% of capacity
Consumer 4: 13188, 87% of capacity
Consumer 5: 14964, 99% of capacity
Consumer 6: 13824, 92% of capacity
Consumer 7: 9540, 63% of capacity
Test failed! Lower than expected amount of kafka messages in sqlite
F
```
The consumers actually wrote all 100000 messages, but Consumer 0 just happened to get less of …
> chore(test): Fixup consumer rebalance test

- migrations/0001_create_inflight_taskactivations.sql
I see almost a 2x performance when running this locally. I promise I will stop working on perf optimization after this.
> perf(store): Add covering index for get_pending_activation

- .github/workflows/ci.yml
Looks like providing an access token gets us a higher Github API request allocation to avoid rate limiting: https://github.com/arduino/setup-protoc#:~:text=to%20avoid%20rate%20limiting
> fix(ci): Add default token to avoid protoc rate limiting

- migrations/0001_create_inflight_taskactivations.sql
- src/inflight_activation_store.rs
- src/inflight_activation_store/store_tests.rs
This makes SQLite enforce that the types of the columns are restricted just to the ones that are
explicitly supported, and does validation on the values being inserted to ensure they are the
correct type.
> fix: Use STRICT when building SQLite table

- src/inflight_activation_store/store_tests.rs
I think we're rounding the wrong value when comparing the 2 timestamps, hence why things are off by one sometimes.
> fix(test): fix flaky test

- python/integration_tests/helpers.py
- python/integration_tests/test_consumer_rebalancing.py
We've been getting quite a few "port is already in use" error leading to the consumer rebalance test to become flaky, add some python code to find ports that are not in use
```
ERROR taskbroker: Task grpc_server failed: GRPC server task failed: tonic::transport::Error(Transport, Os { code: 98, kind: AddrInUse, message: "Address already in use" })
```
> fix(test): Find unused ports for gRPC in rebalance test

- migrations/0001_create_inflight_taskactivations.sql
- src/config.rs
- src/consumer/deserialize_activation.rs
- src/inflight_activation_store.rs
- src/inflight_activation_store/store_tests.rs
- src/main.rs
- src/test_utils.rs
- src/upkeep.rs
- tests/grpc_server_test.rs
There is an edge case with the `remove_at` mechanism which can cause taskbroker to halt. This column is not enough for the taskbroker to differentiate activations that are stuck in sqlite because workers are unable to process them, and activations that are stuck due to workers not being available. 
This PR is responsible for replacing the `remove_at` column with `processing_attempts` which counts the number of times an activation has been reset back from `processing` to `pending` due to processing_deadline exceeding. When `processing_attempts` >= `max_processing_attempts` (defined in configuration), the new `handle_processing_attempts` function in upkeep will move the task to `failed`. Finally, the `handle_failed_tasks` cleans them up.
In this implementation, the `processing_attempts` is …
> feat(processing-attempts): Replace remove_at with processing_attempts

- python/integration_tests/test_consumer_rebalancing.py
- src/consumer/inflight_activation_batcher.rs
- src/consumer/inflight_activation_writer.rs
- src/consumer/kafka.rs
- src/consumer/os_stream_writer.rs
Reducer flush now returns
```rust
Result<Option<Self::Output>, ...>
```
instead of 
```rust
Result<Self::Output, ...>
```
So that it can signal that it yielded no value after a flush call.
This is useful for things like "the reducer is full but the db is also full", so the flush is a noop, the offsets do not get committed.
> feat(kafka): update reducer interface

- src/config.rs
With most of our time math only having second resolution there isn't much reason to run upkeep more frequently than once a second, as the only step that will apply is the completed task garbage collection.
> fix(config) Reduce the default upkeep interval

- src/config.rs
- src/inflight_activation_store.rs
With sync=normal we *could* lose entries in the WAL if the machine were to die abruptly. By forcing a sync on each batch write we can ensure that we won't lose tasks between kafka and sqlite.
> fix: flush WAL on each commit to the store

- src/upkeep.rs
During sandbox testing, I realized we aren't writing the `discarded` count or `expired` count to the upkeep log. This small PR does that and emits a discarded count metric.
> chore(metrics): Add discarded and expires count to upkeep logs and emit metric

- migrations/0001_create_inflight_taskactivations.sql
The queries that the upkeep thread uses have different indexes from the get pending activation query. Add more indexes to account for those queries as well.
These were tested locally, just to ensure that they get used as expected.
```
sqlite> EXPLAIN QUERY PLAN UPDATE inflight_taskactivations SET processing_deadline = null, status = "Failure" WHERE processing_deadline < now() and at_most_once = TRUE AND status = "Processing";
QUERY PLAN
`--SEARCH inflight_taskactivations USING INDEX idx_processing_deadline (status=? AND processing_deadline<?)
sqlite> EXPLAIN QUERY PLAN UPDATE inflight_taskactivations SET status = "FAILURE" WHERE processing_attempts >= 10 AND status = "PROCESSING";
QUERY PLAN
`--SEARCH inflight_taskactivations USING INDEX idx_processing_attempts (status=? AND …
```
> fix(index): Add indexes for the upkeep queries that run

- python/requirements-dev.txt
Updating devservices to 1.0.17: https://github.com/getsentry/devservices/releases/tag/1.0.17
> chore(devservices): Bumping the version of devservices to latest

- src/config.rs
The `max_processing_deadline` default is not used anywhere in taskbroker. Instead the default for this value is defined when the activation is first created (in sentry) [here](https://github.com/getsentry/sentry/blob/4c1f5d4bcf580e6f5727e25e23cce216d9f98fa7/src/sentry/taskworker/constants.py#L1).
> chore(settings): Remove unused max-processing-deadline config

- src/upkeep.rs
We are already capturing this the number of tasks that are exceeded processing deadline. We should write this in our upkeep log.
> chore(upkeep): Add processing_deadline_reset to upkeep logs

- src/config.rs
- src/main.rs
Using the tokio::main macro meant that it wasn't easy to configure the runtime itself using the configuration.
Change the main to not use the macro, and add an option to set the worker threads.
There is also the TOKIO_WORKER_THREADS environment variable, but this felt like a more consistent way of configuring things.
> fix(main): Change to allow passing parameters to the tokio runtime

- src/grpc_server.rs
- src/upkeep.rs
This is related to the bugs around task processing deadlines. The metric to track task execution time was not accurate since it was ignoring the case when the processing deadline had passed.
This also tracks how often a task had its processing count incremented, not just the times the task was discarded after exceeding the increment.
> fix(metrics): Update metrics on processing and execution times

- python/integration_tests/test_upkeep_expiry.py
- src/inflight_activation_store.rs
- src/inflight_activation_store/tests.rs
- src/upkeep.rs
When upkeep needs to handle a large number of deadlines and discards at once, this locks up sqlite for quite a bit. As a result, this is causing a significant decrease in throughput in our sandbox testing. This PR splits out the processing attempts work out of the processing deadline call to sqlite in hopes to reduce the total time sqlite is blocked for when we see a large influx of tasks that need to be discarded after a restart.
> feat(upkeep): Separate processing deadline attempts

- src/config.rs
A taskworker can restart for many reasons: sentry deploy, k8s scheduler eviction, preemption, etc. I think default of `5`  is a bit more forgiving in these cases.
> chore(config): Raise max processing attempts

- src/main.rs
- src/store/inflight_activation.rs
- src/upkeep.rs
Doing many writes/deletes to sqlite can result in a fragmented database that may be underperforming. By running sqlite's incremental_vacuum we can reclain the empty pages and compact the database and indexes.
> feat: Add incremental vacuum

- src/config.rs
- src/store/inflight_activation.rs
In our sandbox testing, we are currently seeing performance issues when taskbroker is running for more than 10-15mins. I have a theory that this is due to how checkpoint is being executed. Pulling sqlite from the sandbox during the degraded state, I observed that the WAL file is almost the same size as the database file. When we explicitly call `wal_checkpoint` in passive mode, there is no guarantee that WAL is actually flushed, instead sqlite just checkpoints as many frames as possible without waiting for readers or writers to finish. At each call, we should be able to verify how many pages are written to the WAL file and how many have moved into the database. The wal_checkpoint pragma returns a single row with three integer columns that tells us this. See …
> feat(inflight-store): Add checkpointing log

- src/config.rs
- src/store/inflight_activation.rs
These logs have't root caused the performance degradation issue (yet?), but I think they could be useful long term. This PR makes this a permanent metric.
> metrics(store): Make wal checkpoint log a metric

- migrations/0001_create_inflight_taskactivations.sql
After testing these indexes in production, they have shown to actually slow down the throughput of the servers.
Before adding the indexes: https://app.datadoghq.com/s/FH6-Y3/4ay-hjm-jc4
After adding the indexes: https://app.datadoghq.com/s/FH6-Y3/pgc-nrd-sb2
> fix(sqlite): Remove upkeep indexes

- src/config.rs
- src/main.rs
Removes the config that allows us to specify how many tokio workers we would like, as it does not change our throughput
> ref(config): Remove tokio worker_threads config

- src/store/inflight_activation.rs
Sqlite allows multiple readers but a single writer, since we are a write heavy application we set our connection pool max connection to 1 to prevent `database is locked` error. But a small percentage of our query is actually only read, and with WAL we can do them concurrently. This pr separates the pool into a read and write pool so these queries can be concurrent.
> pref(store): Separate sqlite into read and write pool

- Dockerfile
- Use the same operating system base image.
- Install all of openssl in the runtime image.
> fix: Fix broken SSL in runtime image

- Dockerfile
- cloudbuild.yaml
Rename these values as they were using the old project name.
> fix: Rename variables used to build images

- src/kafka/consumer.rs
The consumers reduce loop has a check to see whether or not a reducer can insert messages or be flushed. If it's not able to do either, it will wait for a set amount of time before checking again (1s). This PR lowers that time to 250ms, as we are seeing the sqlite database becoming empty.
> ref(kafka): allow consumer to repoll reducers more frequently

- src/kafka/inflight_activation_batcher.rs
- src/main.rs
This is simpler implementation of dropping tasks without the processing strategy change described in: https://github.com/getsentry/taskbroker/pull/258. Instead, this change is made on the reduce step specifically in the `InflightActivationBatcher`. If the task name is found in the runtime config, then do not push into the buffer and emit a metric.
> feat(killswitch): Drop task due to killswitch in batcher

- CODEOWNERS
Refs getsentry/security-as-code#1329
> chore: Rename team in codeowners

- src/config.rs
- src/kafka/inflight_activation_batcher.rs
- src/kafka/inflight_activation_writer.rs
Increase our db batch size to be 1024 from 128, since this is shown to have optimal performance. Also rename it from `pending_buffer_count` to `db_insert_batch_size` to make it consistent with other consumer terminologies
> ref(config): Rename and increase write batch size

- .github/workflows/ci.yml
- Dockerfile
- config/config-dev.yaml
- config/config-sentry-dev.yaml
Using a config file instead of the default config specified in code is a bit of a footgun.
> ref(docker): Stop using config files

- .cargo/config.toml
- gocd/templates/bash/check-cloudbuild.sh
- gocd/templates/bash/check-github-runs.sh
- gocd/templates/bash/deploy.sh
- gocd/templates/bash/wait-canary.sh
- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
- gocd/templates/pipelines/taskbroker.libsonnet
- gocd/templates/taskbroker.jsonnet
- src/kafka/consumer.rs
- Create a basic pipeline with canary support.
- Wait 5 min between canary and full deploy.
- Use the `service` and `env` labels for deployment like we do for other applications.
- Initially only s4s will be deployed to.
Refs #209
> feat: Start gocd pipeline for taskbroker

- src/kafka/consumer.rs
- src/main.rs
1. Changes the base case of the `@reducer` internal rule to 0 reducers from 1 reducers to make the base case much simpler
2. Changes the reducer chaining symbol from `=>` to `,` for aesthetics
Verified that the generated code is the same
https://www.diffchecker.com/Zgz3tIxc/
> ref(consumer): clean up processing_strategy macro

- .github/workflows/ci.yml
- .github/workflows/image.yml
Using version tags or no specifier at all can open us up to dependency attacks.
Pinning the SHA is a strong mitigation.
See: https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
> ci: pin github actions

- gocd/templates/bash/deploy.sh
The default type is deployment, but taskbroker is a statefulset.
> fix(deploy) Target statefulset with deploy

- src/config.rs
- src/kafka/deserialize_activation.rs
- src/main.rs
When a countdown task is processed by the broker, we should limit the countdown duration. This is used to avoid erroneous  tasks from sitting in sqlite indefinitely. The default is set to 1hr and can be configured as an environment variable. Tasks greater than this limit is reduced to the this limit.
> feat(tasks): Set maximum limit for delayed tasks

- .github/workflows/ci.yml
- Makefile
- python/integration_tests/test_upkeep_delay.py
- python/requirements-dev.txt
This PR is responsible for testing the end-to-end flow of delayed tasks within taskbroker and adding this test as a required check in CI.
This test is responsible for checking the integrity of the countdown mechanism responsible for delaying tasks to be executed at a later time. This functionality is made possible by the the upkeep thread of taskbroker which is responsible for shifting tasks from the delay state to the pending state after the countdown has elapsed. In this integration test, an initial amount of messages is produced to kafka with a set delay time. These messages are first written into sqlite with a delay state. During an interval, the upkeep thread periodically checks whether a delayed tasks can be updated. This process continues until all tasks have been shifted to a …
> feat(integration-test): Delayed task integration test

- src/grpc/server.rs
Also add the metric to set task. This can be used to show product teams how long it's taking for the workers to start processing their tasks.
> fix: Add namespace to the timing metric

- src/config.rs
- src/kafka/inflight_activation_writer.rs
- src/upkeep.rs
Currently, if a very large influx of delayed tasks are produced to kafka, there is nothing stopping from the sqlite from growing unboundedly and running out of disk. This PR is responsible for adding a upper limit to the number of delayed tasks that can be stored in sqlite at a given moment. If an incoming batch exceeds this number, then the reduce step will stop receiving messages in its buffer, which bubbles up the pipeline and stops the consumer from reading more messages from kafka.
This has a few implications:
- Since we write in batches, we do not distinguish between delayed tasks and regular tasks at the reduce step.
- Therefore, if the incoming batch causes either the `max_pending_count` or `max_delay_count` to exceed, then emit backpressure. This means that either of these limits …
> feat(reduce): Backpressure when delay task limit reached

- README.md
- src/config.rs
We don't want debug logging enabled in devservices usage or production.
Fixes #329
> fix: Make logging info level by default

- python/integration_tests/test_upkeep_expiry.py
- src/kafka/inflight_activation_batcher.rs
- src/store/inflight_activation.rs
- src/store/inflight_activation_tests.rs
- src/upkeep.rs
This PR is responsible for dropping expired tasks earlier. When a task get consumed and reaches the reduce step, we now check whether the task is killswitched OR whether the task has already expired. If so, drop the task. By skipping the store + upkeep earlier, we would likely get some more throughput from the consumer when experiencing large backlogs of expired tasks. Additionally, this PR changes the way upkeep does `handle_expired_at()`. Instead of hopping the task from pending -> failure -> complete, just delete the activation immediately. This has two implications:
1. Taskbroker will not support DLQing expired tasks.
2. The expire metric will now indicate that the task has been purged from SQLite (previously, this metric only indicated that the activation has been set from pending to …
> feat(taskbroker): Drop expired tasks early

- src/upkeep.rs
Instead of creating a separate time series for each kind of task state and cleanup action. This pr changes them into a single time series with different tags, so that we just need to put a single time series when creating dashboard.
Also renames the gauge metrics to make them sound less confusing.
> ref(taskworker): make upkeep metrics more ergonomic

- src/config.rs
This setting controls the maximum size that the producer will send to Kafka.
> fix(dlq): Add a way to override the max.messages.bytes in Kafka

- src/grpc/server.rs
Currently, our latency metric can incorrectly account for a task's delayed time. Since the latency metric is the duration between Kafka receive time and the time at which the activation was given to worker, delayed tasks can incorrectly skew this metric. Before emitting the metric, if a task was delayed, subtract the duration that it was delayed for, then emit its latency.
> fix(metric): Account for delayed tasks in latency metric

- src/grpc/server.rs
When auditing our metrics, I noticed we were missing a metric that captures where a task was failed. Currently in the taskbroker system, there are two places a task can be set to a failed state:
1. A task exceeds its processing attempts. Upkeep is responsible for failing the task. We capture this metric via `"upkeep.cleanup_action", "kind" => "mark_processing_attempts_exceeded_as_failure"` 
2. A task fails to process in taskworker (e.g. task name does not exist in registry, uncaught exception, etc.). Taskworker will manually set the task status via gRPC endpoint.
This PR captures the metric for scenario 2. This will give us a more holistic picture of where tasks are being failed in taskbroker.
> metric(taskbroker): Capture metric for tasks being set to failed state by taskworker

- src/main.rs
- src/upkeep.rs
If a message can't be written to the DLQ, instead of holding on to it indefinitely log the message out and discard the message.
> ref(dlq): Discard messages that fail to go to the DLQ

- Cargo.lock
- Cargo.toml
- src/store/inflight_activation_tests.rs
- src/upkeep.rs
Bumps the proto version to 0.2.0, which adds the new fields to allow tasks to define delay upon a retry.
During upkeep, upon cloning/serializing a failed task for retry, we set the `delay` field if an activation has a `delay_on_retry` set.
Also adds a few unit tests as I forgot about this cloning/serialization part when implementing the original retry mechanism.
Worker changes
https://github.com/getsentry/sentry/pull/91197
> feat(taskbroker): Add delay on retry

- .github/workflows/ci.yml
- Makefile
- python/integration_tests/test_failed_tasks.py
- python/integration_tests/test_upkeep_expiry.py
- python/requirements-dev.txt
This tests is responsible for ensuring that failed tasks are properly handled by taskbroker. When these tasks are failed, taskbroker is responsible for discarding or deadlettering the task according to the task's configuration. This occurs in the upkeep thread.
To accomplish this, the test starts a taskworker and a taskbroker in separate threads. Synchronization events are use to instruct the taskworker when start processing and shutdown. The taskworker will purposely fail to process a task and set it to a failed state. During the upkeep interval, the upkeep thread will appropriately discard and deadletter tasks. Finally, the total number of discarded and deadlettered tasks are validated.
> feat(test): Discard and DLQ failed task integration test

- .github/workflows/ci.yml
As of sentry-protos 0.2.0, we're including generated code in the rust crates and no longer need to compile protobuf bindings during compile.
> fix(ci) Don't install protoc

- devservices/programs.conf
- python/requirements-dev.txt
This bumps devservices to version 1.1.5
https://github.com/getsentry/devservices/releases/tag/1.1.5
It also adds a programs.conf file to specify the entrypoint for running the relay development server to devservices
> chore(devservices): Bump devservices to 1.1.5

- Cargo.toml
Building rdkafka with `ssl` support that includes SASL.
Testing the image:
```
$ docker run -it --rm -e TASKBROKER_KAFKA_SECURITY_PROTOCOL=sasl_plaintext -e TASKBROKER_KAFKA_SASL_MECHANISM=SCRAM-SHA-256 us-central1-docker.pkg.dev/sentryio/taskbroker/image:853721eb817033db71570177cc3324ba0e4e9b52 ./taskbroker | grep panicked
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
thread 'tokio-runtime-worker' panicked at /taskbroker/src/kafka/consumer.rs:58:14:
2025-04-30T10:30:43.504017Z ERROR taskbroker: Task consumer panicked: JoinError::Panic(Id(12), "Consumer creation failed: KafkaError (Client creation error: sasl.username and sasl.password must be set)", ...)
```
> feat(security): add support for SASL authentication on Kafka connections

- src/upkeep.rs
This log message is the bulk of our logging, and it isn't that useful in production as we also have metrics for all the attributes being logged here.
> fix: Reduce logging volume on brokers

- gocd/templates/taskbroker.jsonnet
`include_regions` is a little non-intuitive, it's not including to an empty list but including to a default list (all `getsentry` 'region mode' regions).  `include_regions` is used for adding `control` to specific pipelines as we run a subset of our services for `control`.
To limit to regions we want to deploy to we need to use `exclude_regions` which removes the provided list of regions from the default list.
> fix(gocd): Use exclude_regions

- Cargo.toml
Adds debug symbols to production binary. This increases the binary size, but also means we don't need to upload the source map to sentry.
> ref(tele): Add debug info for release

- Cargo.lock
- src/config.rs
This pr https://github.com/getsentry/taskbroker/pull/326 forgot to add open ssl to the Cargo.lock file after updating Cargo.toml. Everytime we run cargo check, cargo will try and add it.
> ref(build): Add missing dependency to Cargo.lock

- .github/workflows/image.yml
This one is missing.
Please make sure that `DOCKER_HUB_RW_TOKEN` GHA environment secret is available on this repository.
Further questions: Should we push taskworker to DockerHub too?
> ci: push taskbroker to dockerhub

- .github/workflows/image.yml
The previous build failed because the image that was being tagged was not present on the build runner. Fetching the image first should fix that.
> fix: Pull image before adding tags

- .github/workflows/image.yml
> ci: provide arm64 image for taskbroker

- .github/workflows/release-ghcr-version-tag.yml
I nearly forgot about this, the very last one.
Other repositories:
* sentry https://github.com/getsentry/sentry/pull/88181
* relay https://github.com/getsentry/relay/pull/4532
* symbolicator https://github.com/getsentry/symbolicator/pull/1635
* snuba https://github.com/getsentry/snuba/pull/6997
* vroom https://github.com/getsentry/vroom/pull/576
As we're trying to provide a solution for https://github.com/getsentry/self-hosted/issues/3593
> ci: tag GHCR image with release version

- .craft.yml
- .github/workflows/image.yml
Craft should acquire the Docker image from GHCR instead of Google Artifact Registry. That way we'll include the arm64 platform image.
> ci: acquire release image from ghcr

- benches/store_bench.rs
- build.rs
- src/config.rs
- src/grpc/server.rs
- src/kafka/inflight_activation_writer.rs
- src/kafka/os_stream_writer.rs
- src/runtime_config.rs
- src/store/inflight_activation_tests.rs
- src/test_utils.rs
We've seen an issue emerge in production where sqlite gets overloaded due to high numbers of processing tasks in sqlite. From investigation, I suspect the following negative feedback cycle to exist in taskbroker.
1. A spike in large messages gets written to kafka and consumed by taskbroker.
2. Even after capping the max bytes per batch (default to ~16MB), the consumer thread holds on the the sqlite writer lock for a long time.
3. gRPC becomes slow which makes workers no longer able updates to their tasks quickly (processing -> complete, processing -> failure).
4. More and more tasks stay in the processing state (unboundingly increases).
5. Upkeep cant trigger processing deadlines fast enough to clean up these tasks due to busy sqlite writer.
6. Consumer keeps writing pending tasks to …
> feat(taskworker): Backpressure with max processing count

- gocd/templates/bash/check-cloudbuild.sh
- gocd/templates/bash/check-github-runs.sh
- gocd/templates/bash/deploy.sh
Updating gocd scripts to use console script entry points.
Please see: https://github.com/getsentry/devinfra-deployment-service/pull/698
> ref(gocd): use console script entry points

- .github/workflows/fast-revert.yml
Without the `[bot]` suffix it will lookup `1330327` as a user id, which
is why were were getting @MineCraftSpy as the reverting user
> ci: Fix fast-revert bot name

- src/config.rs
- src/main.rs
- src/upkeep.rs
When taskbrokers are restarted, workers are unable to publish results, and the results they do have get buffered in the worker until the broker is back online. During this restart period, tasks with short deadlines will expire and be made pending again after a broker's first upkeep is completed.
By having an upkeep 'quiet period' we give workers time to flush results which should reduce the number of broker-side deadline resets without a worker kill that we see. This could create a heavier first upkeep if many deadlines have been exceeded, but I think the benefits are worth the tradeoff.
> feat: Add a deadline quiet period after startup

- benches/store_bench.rs
- src/config.rs
- src/store/inflight_activation.rs
- src/store/inflight_activation_tests.rs
Because of clock skew, and overloaded brokers we can end up resetting deadlines in the brokers while workers don't terminate tasks. This leads to duplicate execution and reduces our ability to make progress.
By giving workers an additional 3 seconds of runtime we should be able to work around most clock skew, and many slow broker scenarios. I chose 3 seconds arbitrarily, and am open to changing it.
I've enabled this behavior by default as I think it will be relatively safe as it reduces strictness.
> feat: Add processing deadline grace period

- src/upkeep.rs
This metric is in seconds not milliseconds
> fix: Correct unit suffix on metric

- src/kafka/consumer.rs
- src/kafka/inflight_activation_batcher.rs
- src/test_utils.rs
Fixes the lint error that clippy is complaining about on main.
It seems like it's mostly complaining because `if let` chaining has been stabilized.
> Fix clippy lint

- src/config.rs
In production, we run taskbroker with the following defaults across all our processing pools in all envs:
```
db_max_size: Some(3000000000) # 3GB
max_message_size: 5000000 # 5MB
full_vacuum_on_start: true
```
This PR updates these defaults so we can simplify our override configs in prod.
> fix(taskworker): Update default configs to test values in prod

- gocd/templates/pipelines/taskbroker.libsonnet
The deploy_primary stage is timing out in our SaaS US environment due to large statefulset replicas. This PR bumps that timeout by 10 minutes.
> feat(taskworker): Bump timeout for taskbroker deploy primary stage

- gocd/templates/bash/deploy.sh
The `k8s-deploy` script has a separate timeout arg for watchers: https://github.com/getsentry/devinfra-deployment-service/blob/e77bb0c9c3b6b800a89d2b229cf4b238d618fb0b/gocd_agent/scripts/scripts/k8s/k8s_deploy.py#L358-L363. Since we're hitting timeout limits in US, we should bump this limit until we can use `maxUnavailable` for statefulsets.
> fix(taskbroker): Bump deploy primary timeout in us

- .github/workflows/image.yml
This PR adds jobs in gha for publishing to artifact registry. These images will have the suffix `-gha` so that GoCD will avoid using them for deploys. A PR will follow to cutover GoCD to using these images and cloudbuild images will have a `-cloudbuild` suffix
> feat(ci): Phase 1: Cutover to gha for prod images

- gocd/templates/bash/deploy.sh
The GoCD job is still timing out at 40min. Temporarily bump this to 60min to unblock our pipeline until we can find a better solution to increase deployment velocity.
> fix(taskbroker): Bump deploy watchers to 60min

- gocd/templates/bash/deploy.sh
The GoCD job is still timing out. Temporarily bump this to unblock our pipeline until we can find a better solution to increase deployment velocity.
> fix(taskbroker): Bump deploy primary wait timeout

- Cargo.lock
- Cargo.toml
- benches/store_bench.rs
- src/config.rs
- src/store/inflight_activation.rs
- src/store/inflight_activation_tests.rs
Emit status metrics via sqlite3_db_status to track cache usage, hit/miss counters, lookaside allocator, schema/statement memory, and cache write/spill totals.
> feat(sqlite): Add sqlite db status metrics
