.envrc

Fix mismatched paths that were resulting in pip install running on every cd

fix: Fix direnv path

---

src/consumer/inflight_activation_writer.rs
src/grpc_server.rs
src/upkeep.rs

I suspect this could be the slower part of taskbroker and tracing could help us narrow in on what is slow.

fix: Add more tracing spans to the upkeep task

---

src/consumer/kafka.rs

- Rename handle_os_signal → handle_shutdown_signal because we're not just monitoring os signals anymore
- Add a shutdown guard in the event handler so we signal shutdown to all when it panics.

ref(kafka): Add a shutdown guard in the event handler

---

src/main.rs

In the sandbox the health check is printing logs over and over again, and no setting seems to exist to stop the prints. Remove the health check to confirm whether that really was the culprit.

ref(grpc): Experiment with removing health check

---

Cargo.lock
Cargo.toml
python/integration_tests/helpers.py
python/integration_tests/worker.py
python/requirements-dev.txt
src/consumer/deserialize_activation.rs
src/grpc_server.rs
src/inflight_activation_store.rs
src/main.rs
src/test_utils.rs
src/upkeep.rs
tests/grpc_server_test.rs

We've created a new version of taskbroker protobufs. This PR is responsible for updating all references (and removing deprecated ones) in taskbroker.  
Fixes: https://github.com/getsentry/taskbroker/issues/116

feat(taskbroker): Update to new taskbroker protobufs

---

Makefile
python/integration_tests/helpers.py
python/integration_tests/test_consumer_rebalancing.py
python/integration_tests/test_task_worker_processing.py
python/integration_tests/test_upkeep_retry.py

Some class names, functions names, variables names, and formatting were bugging me. This PR just cleans stuff up.

chore(tests): Clean up integration tests

---

Cargo.lock
Cargo.toml
src/config.rs
src/metrics.rs

Reverts getsentry/taskbroker#140

Revert "ref(tele): Try using DogStatsD exporter"

---

src/config.rs
src/metrics.rs

Adds a `default_metric_tags` to our config so all metrics emitted will be tagged with those key/value pairs.
This is useful for emitting metrics with tags that distinguishes different pods since we're not running out datadog agent as a daemonset.
Use it like so
config file:
```yaml
default_metrics_tags:
key_1: value_1
key_2: value_2
```
envars:
```console
TASKBROKER_DEFAULT_METRICS_TAGS="{key_1=value_1,key_2=value_2}"
```
k8s (according to docs [here](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config)):
```yaml
spec:
containers:
- name: taskbroker
env:
- name: TASKBROKER_DEFAULT_METRICS_TAGS
value: "{host=$(HOSTNAME)}"
```

feat(telemetry): Add config to define metric default tag/values

---

Makefile

devservices no longer removes containers when down is run, so this will need to be run to reset kafka

fix(makefile): Reset-kafka command

---

src/consumer/kafka.rs

Remove some footguns from our kafka consumer
There's a setting for our reducer config called `ReducerWhenFullBehaviour::Flush`. We have code where it checks to see if this config is set and if reducer is full, we flush it. But this code lives in the reduce arm of the `select!`, which is disabled if the consumer is full, because it is relying on the assumption that the reducer can only becomes full by reduce it. The original intention is:
1. The reducer gets initialized and is not full
2. We get a message
3. If the reducer flush timer goes off, flush the reducer
4. If the reducer is full, got to step 6
5. Since the consumer is not full, we call reduce on it, If `ReducerWhenFullBehaviour::Flush` is set and the reducer is full, we flush the reducer
6. Go back to step iii
We can have a …

ref(kafka): minor kafka fixes

---

src/grpc_server.rs

Add a metric that uses the processing deadline as a proxy for when the task was marked processing and started executing on the work.

fix(metrics): Add a metric that tracks how long a task took to complete

---

src/consumer/kafka.rs

Right now when we have a topic with a single partition, and if we start 2 consumers, one of them will crash with a very unintuitive error. This is not desirable as k8s will try and restart them, causing the consumer group to keep rebalancing and the partition being passed around the 2 consumers.
This change makes the consumer not crash and emit a warning that it has no partitions assigned to it. When a partition is finally assigned to it via a rebalance, it will start consumer as expected.

feat(kafka): handle case when there're more consumer than partitions

---

src/config.rs
src/inflight_activation_store.rs

Removes the sqlite sync mode config as I don't think we want people to change this anymore

ref(config): Remove sqlite sync config

---

src/consumer/kafka.rs

Right now, both the error reducer and the regular reducer sends messages downstream to the commit step via mpsc. There could be a situation where either reducer path are in backpressure state but the offset still gets committed from the reducer not in backpressure state.
This stops the error reducer from sending messages to the commit step. The downside is that if all messages are invalid, the consumer group will not make any progress until a valid message is processed. Potentially processing invalid messages multiple times if the consumer restarts without a valid message.

fix(kafka): stop error reducer from committing

---

.github/workflows/ci.yml

- Add llvm-cov and a new github action to collect coverage data

feat: Add test coverage collection

---

Dockerfile
src/config.rs

Reverts getsentry/taskbroker#226

Revert "fix(version): Put the version file in the same place as the executable"

---

Dockerfile
build.rs
src/config.rs
src/lib.rs
src/main.rs

- Put VERSION into /opt during build
- The application loads VERSION with a relative path, and we need to use WORKDIR

fix: Fix VERSION file location

---

src/store/inflight_activation.rs

sqlite performs a bit better when we batch writes with transactions.

fix: Add transaction to processing deadline operations

---

src/grpc/auth_middleware.rs
src/grpc/metrics_middleware.rs

Add basic tests for metrics middleware and an integration test for auth middleware.

fix(coverage) Increase unit test coverage to include middleware

---

VERSION

In the previous PR I only added VERSION to gitignore, it does not actually delete the file

ref: Delete VERSION from repository

---

src/store/inflight_activation.rs
src/upkeep.rs

Replace calls to `.instrument` with macro attributes. This should give us more detail in our tracing data.

fix: Add more tracing spans to RPC endpoints

---

benches/store_bench.rs

Splitting the store benchmarks up into 2 to isolate the functions

perf(store): Split store benchmarks

---

Dockerfile

My last attempt didn't work on cloudbuild.

fix: Try again to get version into generated image

---

benches/store_bench.rs

Fixes the set_status benchmark as we're not calculating the index correctly and not waiting for the join set

fix(bench): fix benchmark test

---

src/kafka/consumer.rs

We stop polling the kafka client when we encounter an error, but this is not desirable as transport failure can result in a value yielded from the rdkafka client.
So if multiple brokers are supplied to the consumer, but a single broker is down, the consumer will crashloop.

ref(kafka): continue to poll consumer on broker transport error

---

src/config.rs

Add support for simple authentication to support work security team is doing.
Refs getsentry/ops#15203
Refs #320

feat: Add support for sasl authentication

---

gocd/templates/taskbroker.jsonnet

Enable deployments for the small single tenants.

feat: Add small single tenants to deploys

---

gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json

Use a newer pipedream version to make customer-3 go away

fix: Update pipedream version

---

src/upkeep.rs

One of the metric name is wrong

fix metric name

---

src/grpc/server.rs
src/store/inflight_activation.rs

We had two copies of this logic.

ref: Consolidate latency logic to InflightActivation

---

src/kafka/inflight_activation_writer.rs

During INC-1158, we received a high influx of tasks at once. When this happened, the number of tasks being written to sqlite per sec nearly 10x'ed. Shortly after, upkeep duration started taking longer which degrades the velocity of the entire pipeline. This PR responsible for adding a metric to capture the time taken to write a batch into sqlite. This is interesting to us because if this time spikes significantly, it blocks concurrent writers to sqlite which could be the ignition to the potential upkeep meltdown described in https://github.com/getsentry/taskbroker/pull/358.

fix(metrics): Add metric for writing batch to store

---

migrations/0003_update_activations_table.sql
src/grpc/server.rs
src/grpc/server_tests.rs
src/kafka/deserialize_activation.rs
src/kafka/inflight_activation_batcher.rs
src/kafka/inflight_activation_writer.rs
src/store/inflight_activation.rs
src/store/inflight_activation_tests.rs
src/test_utils.rs
src/upkeep.rs

Reverts getsentry/taskbroker#375

Revert "feat(sqlite): Remove the need for the protobuf object in processing"

---

.github/workflows/fast-revert.yml

Add a fast revert action to the taskbroker repository.

ref: Add fast revert action to taskbroker

---

.craft.yaml
.github/workflows/release.yml
Dockerfile

- Add release workflow based on how vroom does it.
- Update dockerfile to remove unused arg and set default for version
Refs #267

feat: Add release workflow for creating dockerhub images

---

.github/workflows/image.yml

Hopefully this would work a lot better

ci: build arm64 image (second attempt)

---

devservices/config.yml
devservices/programs.conf
python/requirements-dev.txt

This adds a few changes, including consolidating programs.conf into config.yml.
https://github.com/getsentry/devservices/releases/tag/1.2.1

chore(devservices): Bump devservices to 1.2.1

---

src/store/inflight_activation_tests.rs
src/test_utils.rs

Add more exhaustive assertions for status counts. This could be helpful in the future if we need to refactor InflightActivationStore is implemented.

fix: Improve assertions on status counts

---

src/config.rs

For self-hosted users with external Kafka who needs to connect to Kafka via TLS. Every other repositories has this setting.

feat: SSL configuration options for Kafka

---

.pre-commit-config.yaml
pyproject.toml
python/integration_tests/helpers.py
python/integration_tests/runner.py
python/integration_tests/test_consumer_rebalancing.py
python/integration_tests/test_failed_tasks.py
python/integration_tests/test_task_worker_processing.py
python/integration_tests/test_upkeep_delay.py
python/integration_tests/test_upkeep_expiry.py
python/integration_tests/test_upkeep_retry.py
setup.cfg
uv.lock

This brings this repo up to the python spec: https://www.notion.so/sentry/Standard-Spec-python-22a8b10e4b5d80d4a6e8f7df8c38025f
I've introduced black, isort, flake8, and mypy in accordance with the spec, and fixed all errors.

ref: bring up to python spec
